export * from './account'
export * from './ids'
export * from './pool'
export * from './stake'
export * from './transactions'
export * from './utils'
export * from './layout'
export * from './sslV2'

export const GET_SSL_ANALYTICS = '/ssl-apis/analytics/poolHistory/'
export const GET_SSL_JUPITER = '/ssl-apis/analytics/jupiterHistory/'
export const GET_FUNDING_RATE = '/perps-apis/getFundingRate'
export const GET_LEADERBOARD_DATA = '/perps-apis/getLeaderboardData'
export const GET_LEADERBOARD_DATA_V2 = '/perps-apis/getLeaderboardDataV2'