export const LITEPAPER_ADDRESS = 'https://docs.goosefx.io'
export const LANDING_PAGE_VIDEO = "https://media.goosefx.io/bgvid.mp4"
export const SOCIAL_MEDIAS: { [key: string]: string } = {
  discord: "https://discord.gg/cDEPXpY26q",
  medium: "https://medium.com/goosefx",
  telegram: "https://www.t.me/goosefx",
  twitter: "https://www.twitter.com/GooseFX1"
}

export const SUPPORTED_TOKEN_LIST = [
  'AKRO',
  'ALEPH',
  'BOP',
  'BTC',
  'COPE',
  'CREAM',
  'DXL',
  'ETH',
  'FIDA',
  'FRONT',
  'FTT',
  'HGET',
  'HNT',
  'HXRO',
  'KARMA',
  'KEEP',
  'KIN',
  'LIKE',
  'LINK',
  'LUA',
  'MAPS',
  'MATH',
  'MEDIA',
  'MER',
  'MNGO',
  'MSRM',
  'OXY',
  'PAI',
  'PORT',
  'RAY',
  'ROPE',
  'SAMO',
  'SLRS',
  'SNY',
  'SOL',
  'SRM',
  'STEP',
  'SUSHI',
  'SWAP',
  'SXP',
  'TOMO',
  'TULIP',
  'UBXT',
  'UNI',
  'USDC',
  'USDT',
  'WOO',
  'XRP',
  'YFI',
  'xCOPE'
]
